In [2]:
import numpy as np

In [3]:
np?

In [4]:
a=np.array([1,4,2,5,3])

In [5]:
np.array([2.5,3,4,5])  #upcasting that is converts all into float data type( float is higher priority)

array([2.5, 3. , 4. , 5. ])

In [6]:
type(a)

numpy.ndarray

In [7]:
%%timeit
l1=list(range(5000000))
l2=list(range(5000000))             #comparivtively more time

385 ms ± 4.94 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [8]:
%%time
np_array_1=np.arange(5000000)
np_array_2=np.arange(5000000)       #less time with np

Wall time: 22.3 ms


In [9]:
np.array([1,2,3,4],dtype='float32')      #can convert all of them to float

array([1., 2., 3., 4.], dtype=float32)

In [10]:
np.array([range(i,i+3) for i in [2,4,6]])   #2-D npy array

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

finding mean usinf arrays

In [11]:
from numpy import array,mean
#from numpy import mean          #finding the mean or average
v=array([1,2,3,4,5,6])
print(v)
result=mean(v)
print(result)

[1 2 3 4 5 6]
3.5


In [12]:
from numpy import array,var
#from numpy import var               #finding the variance
v=array([1,2,3,4,5,6])
print(v)
result=var(v,ddof=1)
print(result)

[1 2 3 4 5 6]
3.5


working with pandas

In [25]:
import pandas as pd

In [26]:
pd?

In [29]:
s=pd.Series([1,2,3,np.nan,5,6],
            index=['A','B','C','D','E','F'])       #s is series object that is created

In [30]:
s

A    1.0
B    2.0
C    3.0
D    NaN
E    5.0
F    6.0
dtype: float64

In [32]:
data={'Gender':['F','M','M'],'Emp_ID':['E01','E02','E03'],'Age':[25,27,25]}

In [34]:
df=pd.DataFrame(data,
                columns=['Emp_ID','Gender','Age'])

In [35]:
df

Emp_ID Gender  Age
0    E01      F   25
1    E02      M   27
2    E03      M   25